### ISSUE TITLE
[1.20.1] Error on net.minecraft.server.players.PlayerList

### ISSUE THREAD

**Issue by Eduardo-Malta-Pereira** [Teneted/Tenet#3576]
**Minecraft Version:** 1.20.1

**Mohist Version:** 1.20.1 (build 16b84ddd)

**Operating System:** Windows 10

**Logs:** https://mclo.gs/8gD8ar9

**Mod list:**
- rechiseled-1.1.6-forge-mc1.20.jar  
- SkyblockBuilder-1.20.1-5.1.26.jar  
- HostileNeuralNetworks-1.20.1-5.3.3.jar  
- BrandonsCore-1.20.1-3.2.1.302-universal.jar  
- moonlight-1.20-2.14.1-forge.jar  
- forbidden_arcanus-1.20.1-2.2.6.jar  
- (and others)

**Plugin list:** None

**Description of issue:**  
The server crashes during the mod loading phase due to several mods attempting to access the class `net.minecraft.server.players.PlayerList`. This class is not present or exposed in Mohist's architecture, leading to `NoClassDefFoundError` and preventing these mods from loading correctly. All affected mods work fine on pure Forge 1.20.1 servers. The issue persists even when using the latest build of Mohist. This severely limits compatibility with many Forge-based mods.
