### ISSUE TITLE
[Minecraft 1.20.1] java.lang.NoClassDefFoundError: net/minecraft/server/players/PlayerList

### ISSUE THREAD

**Issue by retrovato123** [Teneted/Tenet#3395]
**Minecraft Version :** Minecraft 1.20.1

**Mohist Version :** All versions 1.20.1

**Operating System :** Linux

**Concerned mod / plugin** : 
CarryOn: https://www.curseforge.com/minecraft/mc-mods/carry-on
Attributizer: https://www.curseforge.com/minecraft/mc-mods/attributizer
ModernFix: https://www.curseforge.com/minecraft/mc-mods/modernfix

**Logs :** https://gist.github.com/retrovato123/8bc1b83d2048c9943c20ac8976704f39

**Steps to Reproduce :**
 1. Start server

**Description of issue :** It only doesn't work with those mods. If I remove them, everything works fine. If I use Forge, they also work, but when I updated MohistMC to 1.20.1, they stopped working. Previous versions do work.

**Comment by Mgazul** [comment]
use modernfix-forge-5.19.4+mc1.20.1

**Comment by retrovato123** [comment]
> modernfix-forge-5.19.4+mc1.20.1

I'm already using modernfix-forge-5.19.4+mc1.20.1

**Comment by TgirlDani** [comment]
I too am having this problem

Minecraft Version : Minecraft 1.20.1

Mohist Version : All versions 1.20.1

Operating System : Windows

Logs: https://gist.github.com/TgirlDani/2a3fcdd3d116ba09727396533a829169


Steps to Reproduce :
Start server

**Comment by Unitei-Dev** [comment]
Look for a problem related to Connector or Fabric mod, it won't help you in any way
