### ISSUE TITLE
[1.16.5] org.bukkit.World.getNearbyLivingEntities in MagicSpells 4.0 beta 8

### ISSUE THREAD

**Issue by zhjlee11** [Teneted/Tenet#2215]
**Minecraft Version :** 1.16.5

**Mohist Version :** mohist-1.16.5-1021-server.jar

**Operating System :** Windows

**Concerned mod / plugin** : [MagicSpells 4.0 beta 8](https://github.com/TheComputerGeek2/MagicSpells)

**Logs :** 
**< Error Message in error txt file >**
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.nisovin.magicspells.MagicSpells$1.execute(MagicSpells.java:1272)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:500)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:467)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463)
	at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1867)
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31)
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:940)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:923)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:917)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:903)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.getNearbyLivingEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
	at com.nisovin.magicspells.spells.targeted.AreaEffectSpell.doAoe(AreaEffectSpell.java:149)
	at com.nisovin.magicspells.spells.targeted.AreaEffectSpell.castSpell(AreaEffectSpell.java:126)
	at com.nisovin.magicspells.Subspell.castReal(Subspell.java:131)
	at com.nisovin.magicspells.Subspell.cast(Subspell.java:117)
	at com.nisovin.magicspells.spells.MultiSpell.castSpell(MultiSpell.java:90)
	at com.nisovin.magicspells.Spell.handleCast(Spell.java:865)
	at com.nisovin.magicspells.Spell.cast(Spell.java:799)
	at com.nisovin.magicspells.Spell.cast(Spell.java:785)
	at com.nisovin.magicspells.listeners.CastListener.castSpell(CastListener.java:156)
	at com.nisovin.magicspells.listeners.CastListener.onPlayerInteract(CastListener.java:74)
	... 28 more

java.lang.NoSuchMethodError: org.bukkit.World.getNearbyLivingEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
	at com.nisovin.magicspells.spells.targeted.AreaEffectSpell.doAoe(AreaEffectSpell.java:149)
	at com.nisovin.magicspells.spells.targeted.AreaEffectSpell.castSpell(AreaEffectSpell.java:126)
	at com.nisovin.magicspells.Subspell.castReal(Subspell.java:131)
	at com.nisovin.magicspells.Subspell.cast(Subspell.java:117)
	at com.nisovin.magicspells.spells.MultiSpell.castSpell(MultiSpell.java:90)
	at com.nisovin.magicspells.Spell.handleCast(Spell.java:865)
	at com.nisovin.magicspells.Spell.cast(Spell.java:799)
	at com.nisovin.magicspells.Spell.cast(Spell.java:785)
	at com.nisovin.magicspells.listeners.CastListener.castSpell(CastListener.java:156)
	at com.nisovin.magicspells.listeners.CastListener.onPlayerInteract(CastListener.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.nisovin.magicspells.MagicSpells$1.execute(MagicSpells.java:1272)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:500)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:467)
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463)
	at net.minecraft.network.play.ServerPlayNetHandler.func_175087_a(ServerPlayNetHandler.java:1867)
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:31)
	at net.minecraft.network.play.client.CAnimateHandPacket.func_148833_a(SourceFile:9)
	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:940)
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:923)
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:917)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:903)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
	at java.lang.Thread.run(Thread.java:748)

Server version: 1.16.5-1021 (MC: 1.16.5)
MagicSpells version: 4.0-Beta-8
Error log date: Sat Jun 11 13:39:26 KST 2022
```

**< Error Message in Bukkit >**
```
[13:39:26 ERROR]: [MagicSpells] AN EXCEPTION HAS OCCURED:
[13:39:26 ERROR]: [MagicSpells]     null (java.lang.reflect.InvocationTargetException)
[13:39:26 ERROR]: [MagicSpells]     org.bukkit.World.getNearbyLivingEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection; (java.lang.NoSuchMethodError)
[13:39:26 ERROR]: [MagicSpells] This error has been saved in the errors folder
```

**Steps to Reproduce :**
 1. When player cast AreaEffectSpell, the spell did not work and occur the error.

ps. [Area Effect Spell Example](https://github.com/TheComputerGeek2/MagicSpells/wiki/AreaEffectSpell)

**Description of issue :** When player cast AreaEffectSpell, the spell did not work and occur the error. But the spell works in Paper 1.16.5.

**Comment by MohistBOT** [comment]
**Hello, thanks for opening this issue!**

Before continuing, please understand that Mohist is a **free** and **open source** software, made by people in **their free time**. Know that we are not able to give any eta about when your issue will get answered or fixed.

> Our team will first check if your issue isn't duplicated. If it's the case, we will close your issue, giving your the number of the other issue so that you can follow its progress. If you are able to do it, please check that your issue isn't duplicated, this would help us a lot.

*Thank you for your patience, and have a nice day (or night)!*
